### PR TITLE
Add Incipias

### PR DESCRIPTION
**Pull request by Tangle10**
I was never told not do to this piecemeal, so... you get this. Also makes sure that an All-Content player gets the Gegno Driller license, previously didn't do that.

### CODE REVIEW

**Comment by tibetiroka** [comment]
Any PR you open is one less I have to make :)

**Comment by tibetiroka** [comment]
It might be better to move the Gegno Driller license to your other PR, as that's already dealing with Gegno stuff.

**Comment by Tangle10** [comment]
> It might be better to move the Gegno Driller license to your other PR, as that's already dealing with Gegno stuff.

Shoot, good idea. Tell you the truth I almost forgot that was a thing...

**Comment by TheGiraffe3** [comment]
~~oh mighty people with merge access~~...

What's the status on this PR?

**Review by TheGiraffe3 — APPROVED** [review]

**Comment by tibetiroka** [comment]
They will be merged in time for the release. All-content doesn't have a continuous version, so we tend to wait until releases to not get stuff mixed up.

**Review by tibetiroka — APPROVED** [review]

**Pull request merged**
